### PR TITLE
Engineering mode

### PR DESCRIPTION
**Pull request by eried**
This includes the example

### CODE REVIEW

**Comment by dzungpv** [comment]
@eried do you test the code for long time and is it stable?

**Comment by eried** [comment]
yes, works nice but the amount of gates is kinda fixed to ld2410 units, here:
```

			engineering_max_gates_moving_distance    	= radar_data_frame_[17]+1;
			engineering_max_gates_stationary_distance	= radar_data_frame_[18]+1;
```

I got an ld2420 to test if it was a good guess (since that one should have more gates) and hilink actually changed the whole protocol to a simpler one, so this engineering mode is good for ld2410

**Comment by eried** [comment]
what I mean is that those max_gates values could be just hardcoded to 9, since there no ld2410 that answers something else there

**Comment by dzungpv** [comment]
Yes, thank you I will test your code

**Comment by dzungpv** [comment]
@eried I have problem with your code, it not auto detect engineering mode automatically. Only work when change the mode by the code at startup. I use HLKRadarTool to change from normal mode to engineering mode and data could not be read.

**Comment by eried** [comment]
ohhh, but is engineering mode saved on the module? I was just adapting this for my use case of engineering mode, but I am using ld2420 now, so it is completely different But this PR could exist just a reference for a future traveller, the previous PR about engineering mode was changing the library too much :)

**Comment by dzungpv** [comment]
@eried  it is OK, I will try to fix it. Off topic but is the ld2420 any better ld2410?

**Comment by eried** [comment]
> @eried it is OK, I will try to fix it. Off topic but is the ld2420 any better ld2410?

Thanks! I tried to make as clean as possible to be PR but suddenly my focus changed. And yes, I think LD2420 is  superior but maybe not for all applications.

-now 3V, not 5V (consumption is much lower, does not get as hot)
-no Bluetooth
-simplified commands
-longer range and engineering mode is much more detailed giving you a giant grid with the measurements instead of only the summary of all the gates

**Comment by dzungpv** [comment]
@eried can you share the lib you using with LD2420? I just order some.

**Pull request closed without merging**
